// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHPYgJoZovHuOyiCERh5DEwHtS2dADk7M',
    appId: '1:237240522440:web:d06daffcf1da32d41337fd',
    messagingSenderId: '237240522440',
    projectId: 'laza-mvp',
    authDomain: 'laza-mvp.firebaseapp.com',
    storageBucket: 'laza-mvp.firebasestorage.app',
    measurementId: 'G-R9YEDQEPLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF9Ir7dhykO_vKmsvVRaF1QruoheKY92c',
    appId: '1:237240522440:android:f086d64b3cb072511337fd',
    messagingSenderId: '237240522440',
    projectId: 'laza-mvp',
    storageBucket: 'laza-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3EDQZEI7WiQt1bnDwCGAxATJRISeZRkM',
    appId: '1:237240522440:ios:5d8f661f80962f241337fd',
    messagingSenderId: '237240522440',
    projectId: 'laza-mvp',
    storageBucket: 'laza-mvp.firebasestorage.app',
    iosBundleId: 'com.example.lazaMvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3EDQZEI7WiQt1bnDwCGAxATJRISeZRkM',
    appId: '1:237240522440:ios:5d8f661f80962f241337fd',
    messagingSenderId: '237240522440',
    projectId: 'laza-mvp',
    storageBucket: 'laza-mvp.firebasestorage.app',
    iosBundleId: 'com.example.lazaMvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHPYgJoZovHuOyiCERh5DEwHtS2dADk7M',
    appId: '1:237240522440:web:7d2b36e8a76b93911337fd',
    messagingSenderId: '237240522440',
    projectId: 'laza-mvp',
    authDomain: 'laza-mvp.firebaseapp.com',
    storageBucket: 'laza-mvp.firebasestorage.app',
    measurementId: 'G-GEV5RK9WZ8',
  );
}
